
const kusaUnskbtItemList = [
    {isSelected: false, name: "あおい"},
    {isSelected: false, name: "あかい"},
    {isSelected: false, name: "うすみどり"},
    {isSelected: false, name: "うすむらさき"},
    {isSelected: false, name: "おうど色"},
    {isSelected: false, name: "オレンジ色"},
    {isSelected: false, name: "かっ色"},
    {isSelected: false, name: "きいろい"},
    {isSelected: false, name: "きみどり"},
    {isSelected: false, name: "金色"},
    {isSelected: false, name: "銀色"},
    {isSelected: false, name: "クリーム色"},
    {isSelected: false, name: "くろい"},
    {isSelected: false, name: "ぐんじょう色"},
    {isSelected: false, name: "こうはく"},
    {isSelected: false, name: "こがね色"},
    {isSelected: false, name: "こげちゃ色"},
    {isSelected: false, name: "こん色"},
    {isSelected: false, name: "しろい"},
    {isSelected: false, name: "しんく"},
    {isSelected: false, name: "すおう色"},
    {isSelected: false, name: "そら色"},
    {isSelected: false, name: "たまむし色"},
    {isSelected: false, name: "ちゃ色"},
    {isSelected: false, name: "つち色"},
    {isSelected: false, name: "にじ色"},
    {isSelected: false, name: "はい色"},
    {isSelected: false, name: "ピンク色"},
    {isSelected: false, name: "ベージュ色"},
    {isSelected: false, name: "べに色"},
    {isSelected: false, name: "みず色"},
    {isSelected: false, name: "みどり"},
    {isSelected: false, name: "むらさき"},
    {isSelected: false, name: "やまぶき色"},
    {isSelected: false, name: "レモン色"},
];

const kusaSkbtNameList = [
    "雑草",
    "薬草",
    "毒草",
    "暴走の種",
    "混乱草",
    "睡眠草",
    "目つぶし草",
    "めぐすり草",
    "すばやさ草",
    "パワーアップ草",
    "弟切草",
    "高飛び草",
    "くねくね草",
    "いやし草",
    "かぐわし草",
    "胃拡張の種",
    "胃縮小の種",
    "ドラゴン草",
    "復活の草",
    "無敵草",
    "不幸の種",
    "命の草",
    "毒消し草",
    "ちからの草",
    "しあわせ草",
    "天使の種",
    "超不幸の種",    
];

