
const makimono = {};

makimono.unskbtNameList = [
    "アシカ",
    "イタチ",
    "イヌ",
    "イルカ",
    "ウサギ",
    "ウシ",
    "ウマ",
    "オオカミ",
    "カッパ",
    "カバ",
    "カメ",
    "カモメ",
    "カラス",
    "カワウソ",
    "キジ",
    "キツネ",
    "キリン",
    "クジラ",
    "コアラ",
    "コウモリ",
    "ゴリラ",
    "サイ",
    "サメ",
    "シカ",
    "シャチ",
    "スズメ",
    "ゾウ",
    "タカ",
    "タヌキ",
    "ツバメ",
    "ドール",
    "トカゲ",
    "トラ",
    "トンビ",
    "ネコ",
    "ネズミ",
    "バク",
    "ハト",
    "ヒツジ",
    "ヒョウ",
    "フクロウ",
    "ブタ",
    "ヘビ",
    "ペンギン",
    "ムササビ",
    "モグラ",
    "ヤギ",
    "ライオン",
    "ラクダ",
    "ラッコ",
    "リス",
    "ロバ",
    "ワシ",
];

// ぬれた、脱出、白紙は除外
makimono.skbtItemList = [
    {name: "混乱の巻物", unskbtName: ""},
    {name: "バクスイの巻物", unskbtName: ""},
    {name: "ゾワゾワの巻物", unskbtName: ""},
    {name: "真空斬りの巻物", unskbtName: ""},
    {name: "識別の巻物", unskbtName: ""},
    {name: "銀封印の巻物", unskbtName: ""},
    {name: "生物集合の巻物", unskbtName: ""},
    {name: "道具寄せの巻物", unskbtName: ""},
    {name: "困った時の巻物", unskbtName: ""},
    {name: "天の恵みの巻物", unskbtName: ""},
    {name: "地の恵みの巻物", unskbtName: ""},
    {name: "メッキの巻物", unskbtName: ""},
    {name: "印増大の巻物", unskbtName: ""},
    {name: "印消しの巻物", unskbtName: ""},
    {name: "おにぎりの巻物", unskbtName: ""},
    {name: "おはらいの巻物", unskbtName: ""},
    {name: "あかりの巻物", unskbtName: ""},
    {name: "迷子の巻物", unskbtName: ""},
    {name: "罠消しの巻物", unskbtName: ""},
    {name: "銀はがしの巻物", unskbtName: ""},
    {name: "壺増大の巻物", unskbtName: ""},
    {name: "吸い出しの巻物", unskbtName: ""},
    {name: "呪いの巻物", unskbtName: ""},
    {name: "罠の巻物", unskbtName: ""},
    {name: "水がれの巻物", unskbtName: ""},
    {name: "魔物部屋の巻物", unskbtName: ""},
    {name: "大部屋の巻物", unskbtName: ""},
    {name: "バクチの巻物", unskbtName: ""},
    {name: "くちなしの巻物", unskbtName: ""},
    {name: "拾えずの巻物", unskbtName: ""},
    {name: "敵加速の巻物", unskbtName: ""},
    {name: "聖域の巻物", unskbtName: ""},
    {name: "全滅の巻物", unskbtName: ""},
    {name: "ねだやしの巻物", unskbtName: ""},
];
