
const udewa = {};

udewa.unskbtNameList = [
    "アキシナイト",
    "アクアマリン",
    "アゲート",
    "アズライト",
    "アパタイト",
    "アマゾナイト",
    "アメジスト",
    "アルマンダイン",
    "アンダルサイト",
    "インカローズ",
    "ウルフェナイト",
    "エメラルド",
    "エンスタタイト",
    "オージャイト",
    "オニキス",
    "オパール",
    "カイヤナイト",
    "ガラス",
    "カルサイト",
    "クリソコーラ",
    "クリソベリル",
    "コーネルピン",
    "サーペンティン",
    "サニディーン",
    "サファイア",
    "ジェイド",
    "シトリン",
    "ジルコン",
    "スフィーン",
    "ダイオプサイト",
    "ダイヤモンド",
    "デマントイド",
    "トパーズ",
    "トルコ石",
    "トルマリン",
    "ネフタイト",
    "パール",
    "パイロープ",
    "フローライト",
    "ヘマタイト",
    "ペリドット",
    "マラカイト",
    "マンダリン",
    "モアサナイト",
    "モルガナイト",
    "ラピスラズリ",
    "リューサイト",
    "ローズクォーツ",
    "ロードナイト",
];

udewa.skbtItemList = [
    {name: "遠投の腕輪", unskbtName: ""},
    {name: "ヘタ投げの腕輪", unskbtName: ""},
    {name: "ボヨヨンの腕輪", unskbtName: ""},
    {name: "連射の腕輪", unskbtName: ""},
    {name: "諸刃の腕輪", unskbtName: ""},
    {name: "痛恨の腕輪", unskbtName: ""},
    {name: "高飛びの腕輪", unskbtName: ""},
    {name: "爆発の腕輪", unskbtName: ""},
    {name: "垂れ流しの腕輪", unskbtName: ""},
    {name: "金垂れ流しの腕輪", unskbtName: ""},
    {name: "罠増しの腕輪", unskbtName: ""},
    {name: "ちからの腕輪", unskbtName: ""},
    {name: "睡眠よけの腕輪", unskbtName: ""},
    {name: "気配察知の腕輪", unskbtName: ""},
    {name: "道具感知の腕輪", unskbtName: ""},
    {name: "大砲強化の腕輪", unskbtName: ""},
    {name: "呪いよけの腕輪", unskbtName: ""},
    {name: "水グモの腕輪", unskbtName: ""},
    {name: "浮遊の腕輪", unskbtName: ""},
    {name: "魔物呼びの腕輪", unskbtName: ""},
    {name: "胃拡張の腕輪", unskbtName: ""},
    {name: "胃縮小の腕輪", unskbtName: ""},
    {name: "弾きよけの腕輪", unskbtName: ""},
    {name: "値切りの腕輪", unskbtName: ""},
    {name: "しあわせの腕輪", unskbtName: ""},
    {name: "混乱よけの腕輪", unskbtName: ""},
    {name: "回復の腕輪", unskbtName: ""},
    {name: "錆よけの腕輪", unskbtName: ""},
    {name: "透視の腕輪", unskbtName: ""},
    {name: "裏道の腕輪", unskbtName: ""},
    {name: "すれちがいの腕輪", unskbtName: ""},
    {name: "毒消しの腕輪", unskbtName: ""},
    {name: "壁抜けの腕輪", unskbtName: ""},
    {name: "忍び足の腕輪", unskbtName: ""},
    {name: "罠師の腕輪", unskbtName: ""},
    {name: "鑑定師の腕輪", unskbtName: ""},
    {name: "百発百中の腕輪", unskbtName: ""},    
];

for (const skbtItem of udewa.skbtItemList) {
    const unskbtName = localStorage.getItem(skbtItem.name);
    if (unskbtName !== null) {
        skbtItem.unskbtName = unskbtName;
    }
}
